<!DOCTYPE html>
<html>
	<head>
		<title>Error</title>
	</head>
	<body>
		<nav class="navbar navbar-default navbar-static-top">
			<div class="container-fluid">

				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>

				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

					<ul class="nav navbar-nav navbar-right">
					</ul>

				</div>
			</div>
		</nav>
		<div class="container">
			<div class="row">
				<div class="col-lg-12 text-center">
					<h1>Sorry something went wrong</h1>
					<h3>Let's get you back to somewhere <a href="/secure/home">familiar</a></h3>
				</div>
			</div>
		</div>


	</body>
</html>
